import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "Verify" : "Verify",
      "Indentity" : "Indentity",
      "Now we need to verify your identity" : "Now we need to verify your identity",
      "Note" : "Note",
      "You are required to must upload both documents after the submit button appeared" : "You are required to must upload both documents after the submit button appeared",
      "Document Max 1 Picture Selected From Camera" : "Document Max 1 Picture Selected From Camera",
      "Document Max 2 Picture Selected From Gallery" : "Document Max 2 Picture Selected From Gallery",
      "Document Max 3 Picture Selected" : "Document Max 3 Picture Selected",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Take a Passport or ID to Check Your Information(Upload at Least 2 document)",
      "Passport Scan" : "Passport Scan",
      "Haven't uploaded yet" : "Haven't uploaded yet",
      "Submit All" : "Submit All",
      "Selfie with your front camera to verify your identity" : "Selfie with your front camera to verify your identity",
      "Selfie" : "Selfie",
      "Add Wallet" : "Add Wallet",
      "Simplify the way you find carriers." : "Simplify the way you find carriers.",
      "Don’t have an account?  " : "Don’t have an account?  ",
      "Skip" : "Skip",
      "Password" : "Password",
      "Add" : "Add",
      "Post Loads" : "Post Loads",
      "Notification" : "Notification",
      "Balance" : "Balance",
      "Continue" : "Continue",
      "Accept" : "Accept",
      "Payable Amount" : "Payable Amount",
      "Lorry" : "Lorry",
      "Since" : "Since",
      "Expiry in" : "Expiry in",
      "Do you want to reject?" : "Do you want to reject?",
      "Rate to" : "Rate to",
      "Loads" : "Loads",
      "UnLoad" : "UnLoad",
      "Routes" : "Routes",
      "Rc Verified" : "Rc Verified",
      "Send offer" : "Send offer",
      "Waiting for offer Response" : "Waiting for offer Response",
      "Waiting for Response" : "Waiting for Response",
      "Proceed" : "Proceed",
      "Refer a Friends, Get \$50" : "Refer a Friends, Get \$50",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "Get \$10 in Credit When Someone Sing Up Using Your Referal Link",
      "Share" : "Share",
      "Edit Profile" : "Edit Profile",
      "Update" : "Update",
      "Post Load" : "Post Load",
      "It is not possible to choose a larry with a your load capacity" : "It is not possible to choose a larry with a your load capacity",
      "Fixed" : "Fixed",
      "Tonne" : "Tonne",
      "Edit Load" : "Edit Load",
      "Contact Details" : "Contact Details",
      "My Self" : "My Self",
      "Load Edited !" : "Load Edited !",
      "Enter Your Loction" : "Enter Your Loction",
      "Select Vehicle type for your load" : "Select Vehicle type for your load",
      "Available" : "Available",
      "Search" : "Search",
      "Book Now" : "Book Now",
      "Sent Request" : "Sent Request",
      "Code" : "Code",
      "Already have an account?  " : "Already have an account?  ",
      "Mobile Number" : "Mobile Number",
      "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password." : "If A Match is Found, The System Sends An Mobile To The User's Registered Mobile Number With Instructions For Resetting Their Password.",
      "Forgot Password" : "Forgot Password",
      "Find Lorry" : "Find Lorry",
      "Faq" : "Faq",
      "Continue With Wallet" : "Continue With Wallet",
      "Wallet information" : "Wallet information",
      "Enter your Price" : "Enter your Price",
      "Bid Now" : "Bid Now",
      "FAQ":"FAQ",
      "Reject" : "Reject",
      "offer" : "offer",
      "Load Tracking Status" : "Load Tracking Status",
      "Accept & Pay" : "Accept & Pay",
      "Lorry Owner Response" : "Lorry Owner Response",
      "Load" : "Load",
      "Info" : "Info",
      "Total Review" : "Total Review",
      "Date of Joining" : "Date of Joining",
      "Route Operation" : "Route Operation",
      "Enter your Feedback" : "Enter your Feedback",
      "Transaction ID" : "Transaction ID",
      "Payment Gateway" : "Payment Gateway",
      "Payment Information" : "Payment Information",
      "Bidder information" : "Bidder information",
      "Bid Response" : "Bid Response",
      "Total Payment" : "Total Payment",
      "Sub Total" : "Sub Total",
      "Payment Method" : "Payment Method",
      "ACCEPT & PAY" : "ACCEPT & PAY",
      "Description" : "Description",
      "Bid Details" : "Bid Details",
      "No" : "No",
      "Yes,Continue" : "Yes,Continue",
      "if you delete this bid you would not be able to view or bid on this load" : "if you delete this bid you would not be able to view or bid on this load",
      "Are you want to delete bid?" : "Are you want to delete bid?",
      "Your required to contact the lorry owner for further communication" : "Your required to contact the lorry owner for further communication",
      "Material" : "Material",
      "Load Process" : "Load Process",
      "Tonnes" : "Tonnes",
      "Date" : "Date",
      "Shortly You get revert !!" : "Shortly You get revert !!",
      "Name" : "Name",
      "Request sent to Lorry Owner !" : "Request sent to Lorry Owner !",
      "Load Details" : "Load Details",
      "Load Posted !" : "Load Posted !",
      "Shortly You get leads !!" : "Shortly You get leads !!",
      "Drop Contact Details" : "Drop Contact Details",
      "Pickup Contact Detail" : "Pickup Contact Detail",
      "Hours" : "Hours",
      "Number of hours" : "Number of hours",
      "Not Fix" : "Not Fix",
      "The number of hours visible load?" : "The number of hours visible load?",
      "What’s your expected price?" : "What’s your expected price?",
      "Post" : "Post",
      "Amount" : "Amount",
      "Per Tonnes" : "Per Tonnes",
      "Fix" : "Fix",
      "Select Vehicle" : "Select Vehicle",
      "Drop Point" : "Drop Point",
      "Pickup Point" : "Pickup Point",
      "Next" : "Next",
      "Number of Tonnes" : "Number of Tonnes",
      "Material Name" : "Material Name",
      "Vehicle Type" : "Vehicle Type",
      "Enter Amount" : "Enter Amount",
      "Operating Routes" : "Operating Routes",
      "Please verify your identity First" : "Please verify your identity First",
      "Become world’s Transporter" : "Become world’s Transporter",
      "Hello.." : "Hello..",
      "Confirm" : "Confirm",
      "Select Payment Gateway" : "Select Payment Gateway",
      "You haven't made any transaction using wallet yet" : "You haven't made any transaction using wallet yet",
      "E-Wallet" : "E-Wallet",
      "Transaction History" : "Transaction History",
      "Total Earning" : "Total Earning",
      "Home" : "Home",
      "Wallet" : "Wallet",
      "Review" : "Review",
      "Terms & Conditions" : "Terms & Conditions",
      "Privacy Policy" : "Privacy Policy",
      "Refer to Friends" : "Refer to Friends",
      "Profile" : "Profile",
      "Contact Us" : "Contact Us",
      "Language" : "Language",
      "LogOut" : "LogOut",
      "My Loads" : "My Loads",
      "Booked Lorries" : "Booked Lorries",
      "Enter new Password" : "Enter new Password",
      "Submit" : "Submit",
      "No Load Placed! Currently You Don't Have Any Loads" : "No Load Placed! Currently You Don't Have Any Loads",
      "COMPLETED" : "COMPLETED",
      "MY CURRENT LOADS" : "MY CURRENT LOADS",
      "Booked Loads" : "Booked Loads",
      "Full Name" : "Full Name",
      "Email Address" : "Email Address",
      "Seems you are new here, Let’s set up your profile." : "Seems you are new here, Let’s set up your profile.",
      "Getting Started!" : "Getting Started!",
      "Verify Account" : "Verify Account",
      "Forgot Password?" : "Forgot Password?",
      "Sign up" : "Sign up",
      "Resend code?" : "Resend code?",
      "OTP Verification" : "OTP Verification",
      "Please, enter the verification code we send to your mobile " : "Please, enter the verification code we send to your mobile ",
      "Login" : "Login",
      "Forgot  Password?" : "Forgot  Password?",
      "Let’s login for explore continues" : "Let’s login for explore continues",
      "Welcome Back!" : "Welcome Back!",
      "Get better rates on every deal." : "Get better rates on every deal.",
      "The right load for the right truck." : "The right load for the right truck.",
      "Search active loads by location and equipment type" : "Search active loads by location and equipment type",
      "We match the right load to the right truck at the right price" : "We match the right load to the right truck at the right price",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "We offer a wide range of problem-solving products designed to help you ship more freight faster",
    },
    'ur_ar': {
      "Verify" : "يؤكد",
      "Indentity" : "المسافة البادئة",
      "Now we need to verify your identity" : "الآن نحن بحاجة للتحقق من هويتك",
      "Note" : "ملحوظة",
      "You are required to must upload both documents after the submit button appeared" : "يجب عليك تحميل كلا الوثيقتين بعد ظهور زر الإرسال",
      "Document Max 1 Picture Selected From Camera" : "مستند بحد أقصى 1 صورة مختارة من الكاميرا",
      "Document Max 2 Picture Selected From Gallery" : "وثيقة ماكس 2 صورة مختارة من المعرض",
      "Document Max 3 Picture Selected" : "تم تحديد المستند بحد أقصى 3 صور",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "خذ جواز سفر أو بطاقة هوية للتحقق من معلوماتك (قم بتحميل مستندين على الأقل)",
      "Passport Scan" : "مسح جواز السفر",
      "Haven't uploaded yet" : "لم يتم تحميلها بعد",
      "Submit All" : "إرسال الكل",
      "Selfie with your front camera to verify your identity" : "صورة شخصية بالكاميرا الأمامية للتحقق من هويتك",
      "Selfie" : "صورة شخصية",
      "Add Wallet" : "أضف المحفظة",
      "Add" : "يضيف",
      "Post Loads" : "نشر الأحمال",
      "Notification" : "إشعار",
      "Balance" : "توازن",
      "Continue" : "يكمل",
      "Accept" : "يقبل",
      "Payable Amount" : "المبلغ المستحق",
      "Lorry" : "شاحنة",
      "Since" : "منذ",
      "Expiry in" : "انتهاء الصلاحية في",
      "Do you want to reject?" : "هل تريد الرفض؟",
      "Rate to" : "معدل ل",
      "Loads" : "الأحمال",
      "UnLoad" : "إلغاء التحميل",
      "Routes" : "الطرق",
      "Rc Verified" : "تم التحقق من اتفاقية روتردام",
      "Send offer" : "إرسال العرض",
      "Waiting for offer Response" : "في انتظار الرد على العرض",
      "Waiting for Response" : "في انتظار الرد",
      "Proceed" : "يتابع",
      "Refer a Friends, Get \$50" : "قم بإحالة الأصدقاء واحصل على 50 دولارًا",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "احصل على رصيد بقيمة \$10 عندما يقوم شخص ما بالتسجيل باستخدام رابط الإحالة الخاص بك",
      "Share" : "يشارك",
      "Edit Profile" : "تحرير الملف الشخصي",
      "Update" : "تحديث",
      "Post Load" : "تحميل آخر",
      "It is not possible to choose a larry with a your load capacity" : "ليس من الممكن اختيار لاري بسعة التحميل الخاصة بك",
      "Fixed" : "مُثَبَّت",
      "Tonne" : "طن",
      "Edit Load" : "تحرير التحميل",
      "Contact Details" : "تفاصيل الاتصال",
      "My Self" : "نفسي",
      "Load Edited !" : "تحميل تم تحريره!",
      "Enter Your Loction" : "أدخل موقعك",
      "Select Vehicle type for your load" : "حدد نوع المركبة لحمولتك",
      "Available" : "متاح",
      "Search" : "يبحث",
      "Book Now" : "احجز الآن",
      "Sent Request" : "الطلب المرسل",
      "Simplify the way you find carriers." : "بسّط طريقة العثور على شركات النقل.",
      "Don’t have an account?  " : "ليس لديك حساب؟",
      "Skip" : "يتخطى",
      "Faq" : "التعليمات",
      "Continue With Wallet" : "تواصل مع المحفظة",
      "Wallet information" : "معلومات المحفظة",
      "Enter your Price" : "أدخل السعر الخاص بك",
      "Bid Now" : "المزايدة الآن",
      "Reject" : "يرفض",
      "offer" : "يعرض",
      "Load Tracking Status" : "حالة تتبع التحميل",
      "Accept & Pay" : "قبول والدفع",
      "Lorry Owner Response" : "رد مالك الشاحنة",
      "Load" : "حمولة",
      "Info" : "معلومات",
      "Total Review" : "المراجعة الإجمالية",
      "Date of Joining" : "تاريخ الإنضمام",
      "Route Operation" : "عملية الطريق",
      "Enter your Feedback" : "أدخل ملاحظاتك",
      "Transaction ID" : "رقم المعاملة",
      "Payment Gateway" : "بوابة الدفع",
      "Payment Information" : "معلومات الدفع",
      "Bidder information" : "معلومات مقدم العرض",
      "Bid Response" : "استجابة العطاء",
      "Total Payment" : "المبلغ الإجمالي",
      "Sub Total" : "المجموع الفرعي",
      "Payment Method" : "طريقة الدفع او السداد",
      "ACCEPT & PAY" : "قبول والدفع",
      "Description" : "وصف",
      "Bid Details" : "تفاصيل العطاء",
      "No" : "لا",
      "Yes,Continue" : "نعم، استمر",
      "if you delete this bid you would not be able to view or bid on this load" : "إذا قمت بحذف عرض الأسعار هذا، فلن تتمكن من عرض هذا التحميل أو تقديم عرض عليه",
      "Are you want to delete bid?" : "هل تريد حذف العطاء؟",
      "Your required to contact the lorry owner for further communication" : "مطلوب منك الاتصال بمالك الشاحنة لمزيد من التواصل",
      "Material" : "مادة",
      "Load Process" : "عملية التحميل",
      "Tonnes" : "طن",
      "Date" : "تاريخ",
      "Shortly You get revert !!" : "قريبا يمكنك العودة !!",
      "Name" : "اسم",
      "Request sent to Lorry Owner !" : "تم إرسال الطلب إلى مالك الشاحنة!",
      "Find Lorry" : "ابحث عن شاحنة",
      "Load Details" : "تفاصيل التحميل",
      "Load Posted !" : "تحميل نشرت!",
      "Shortly You get leads !!" : "قريبا تحصل على عملاء محتملين !!",
      "Mobile Number" : "رقم الهاتف المحمول",
      "Drop Contact Details" : "إسقاط تفاصيل الاتصال",
      "Pickup Contact Detail" : "تفاصيل الاتصال بيك اب",
      "Hours" : "ساعات",
      "Number of hours" : "عدد الساعات",
      "Not Fix" : "غير ثابت",
      "The number of hours visible load?" : "عدد ساعات الحمل المرئية؟",
      "What’s your expected price?" : "ما هو سعرك المتوقع؟",
      "Post" : "بريد",
      "Amount" : "كمية",
      "Per Tonnes" : "لكل طن",
      "Fix" : "يصلح",
      "Select Vehicle" : "اختر مركبة",
      "Drop Point" : "نقطة الإسقاط",
      "Pickup Point" : "نقطة الالتقاط",
      "Next" : "التالي",
      "Number of Tonnes" : "عدد الأطنان",
      "Material Name" : "اسم المادة",
      "Vehicle Type" : "نوع السيارة",
      "Enter Amount" : "أدخل المبلغ",
      "Operating Routes" : "طرق التشغيل",
      "Please verify your identity First" : "يرجى التحقق من هويتك أولا",
      "Become world’s Transporter" : "تصبح الناقل في العالم",
      "Hello.." : "مرحبًا..",
      "Confirm" : "يتأكد",
      "Select Payment Gateway" : "حدد بوابة الدفع",
      "You haven't made any transaction using wallet yet" : "لم تقم بإجراء أي معاملة باستخدام المحفظة حتى الآن",
      "E-Wallet" : "المحفظة الإلكترونية",
      "Transaction History" : "تاريخ المعاملات",
      "Total Earning" : "مجموع الأرباح",
      "Home" : "بيت",
      "Wallet" : "محفظة",
      "Review" : "مراجعة",
      "Terms & Conditions" : "البنود و الظروف",
      "Privacy Policy" : "سياسة الخصوصية",
      "Refer to Friends" : "الرجوع إلى الأصدقاء",
      "Profile" : "حساب تعريفي",
      "Contact Us" : "اتصل بنا",
      "Language" : "لغة",
      "FAQ" : "التعليمات",
      "LogOut" : "تسجيل خروج",
      "My Loads" : "أحمالي",
      "Booked Lorries" : "الشاحنات المحجوزة",
      "Enter new Password" : "أدخل كلمة المرور الجديدة",
      "Submit" : "يُقدِّم",
      "No Load Placed! Currently You Don't Have Any Loads" : "لم يتم وضع أي تحميل! حاليا ليس لديك أي أحمال",
      "COMPLETED" : "مكتمل",
      "MY CURRENT LOADS" : "أحمالي الحالية",
      "Booked Loads" : "الأحمال المحجوزة",
      "Full Name" : "الاسم الكامل",
      "Email Address" : "عنوان البريد الإلكتروني",
      "Seems you are new here, Let’s set up your profile." : "يبدو أنك جديد هنا، فلنقم بإعداد ملفك الشخصي.",
      "Getting Started!" : "ابدء!",
      "Verify Account" : "التحقق من الحساب",
      "Forgot Password" : "هل نسيت كلمة السر",
      "Sign up" : "اشتراك",
      "Resend code?" : "أعد إرسال الرمز؟",
      "Password" : "كلمة المرور",
      "OTP Verification" : "التحقق من OTP",
      "Please, enter the verification code we send to your mobile " : "من فضلك قم بإدخال رمز التحقق الذي أرسلناه إلى هاتفك المحمول",
      "Login" : "تسجيل الدخول",
      "Forgot  Password?" : "هل نسيت كلمة السر؟",
      "Let’s login for explore continues" : "دعنا نسجل الدخول لمواصلة الاستكشاف",
      "Welcome Back!" : "مرحبًا بعودتك!",
      "Get better rates on every deal." : "احصل على أسعار أفضل على كل صفقة.",
      "The right load for the right truck." : "الحمولة المناسبة للشاحنة المناسبة.",
      "Search active loads by location and equipment type" : "بحث الأحمال النشطة حسب الموقع ونوع المعدات",
      "We match the right load to the right truck at the right price" : "نحن نطابق الحمولة المناسبة بالشاحنة المناسبة بالسعر المناسب",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "نحن نقدم مجموعة واسعة من منتجات حل المشكلات المصممة لمساعدتك على شحن المزيد من البضائع بشكل أسرع",
    },
    'af_ge': {
        "Verify" : "Verifieer",
        "Indentity" : "Indentiteit",
        "Now we need to verify your identity" : "Nou moet ons jou identiteit verifieer",
        "Note" : "Let wel",
        "You are required to must upload both documents after the submit button appeared" : "Daar word van u verwag om beide dokumente op te laai nadat die indien-knoppie verskyn het",
        "Document Max 1 Picture Selected From Camera" : "Dokument Maks. 1 prent gekies uit kamera",
        "Document Max 2 Picture Selected From Gallery" : "Dokument Max 2 Prent gekies uit Galery",
        "Document Max 3 Picture Selected" : "Dokument Maks. 3 Prent gekies",
        "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Neem 'n paspoort of ID om jou inligting na te gaan (laai ten minste 2 dokumente op)",
        "Passport Scan" : "Paspoort skandering",
        "Haven't uploaded yet" : "Het nog nie opgelaai nie",
        "Submit All" : "Dien alles in",
        "Selfie with your front camera to verify your identity" : "Selfie met jou voorste kamera om jou identiteit te verifieer",
        "Selfie" : "Selfie",
        "Add Wallet" : "Voeg beursie by",
        "Add" : "Voeg by",
        "Post Loads" : "Plaas vragte",
        "Notification" : "Kennisgewing",
        "Balance" : "Balans",
        "Continue" : "Gaan voort",
        "Accept" : "Aanvaar",
        "Payable Amount" : "Betaalbare bedrag",
        "Lorry" : "Lorrie",
        "Since" : "Sedert",
        "Expiry in" : "Verval in",
        "Do you want to reject?" : "Wil jy verwerp?",
        "Rate to" : "Beoordeel na",
        "Loads" : "Vragte",
        "UnLoad" : "Laai af",
        "Routes" : "Roetes",
        "Rc Verified" : "Rc geverifieer",
        "Send offer" : "Stuur aanbod",
        "Waiting for offer Response" : "Wag vir aanbodreaksie",
        "Waiting for Response" : "Wag vir reaksie",
        "Proceed" : "Gaan voort",
        "Refer a Friends, Get \$50" : "Verwys 'n vriende, kry \$50",
        "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "Kry \$10 in krediet wanneer iemand sing met jou verwysingskakel",
        "Share" : "Deel",
        "Edit Profile" : "Wysig profiel",
        "Update" : "Dateer op",
        "Post Load" : "Poslaai",
        "It is not possible to choose a larry with a your load capacity" : "Dit is nie moontlik om 'n larrie met 'n jou laaivermoë te kies nie",
        "Fixed" : "Vaste",
        "Tonne" : "Tonne",
        "Edit Load" : "Wysig Laai",
        "Contact Details" : "Kontakbesonderhede",
        "My Self" : "My Self",
        "Load Edited !" : "Laai geredigeer!",
        "Enter Your Loction" : "Voer jou ligging in",
        "Select Vehicle type for your load" : "Kies Voertuigtipe vir jou vrag",
        "Available" : "Beskikbaar",
        "Search" : "Soek",
        "Book Now" : "Bespreek nou",
        "Sent Request" : "Versoek gestuur",
        "Simplify the way you find carriers." : "Vereenvoudig die manier waarop jy draers vind.",
        "Don’t have an account?  " : "Het jy nie 'n rekening nie?",
        "Skip" : "Huppel",
        "Faq" : "Gereelde vrae",
        "Continue With Wallet" : "Gaan voort met Wallet",
        "Wallet information" : "Beursie inligting",
        "Enter your Price" : "Voer jou prys in",
        "Bid Now" : "Bied nou",
        "Reject" : "Verwerp",
        "offer" : "bied",
        "Load Tracking Status" : "Laai dopstatus",
        "Accept & Pay" : "Aanvaar & Betaal",
        "Lorry Owner Response" : "Vragmotor-eienaar se reaksie",
        "Load" : "Laai",
        "Info" : "Inligting",
        "Total Review" : "Totale resensie",
        "Date of Joining" : "Datum van aansluiting",
        "Route Operation" : "Roete Operasie",
        "Enter your Feedback" : "Voer jou terugvoer in",
        "Transaction ID" : "Transaksie ID",
        "Payment Gateway" : "Betalingspoort",
        "Payment Information" : "Betaling Inligting",
        "Bidder information" : "Bieër inligting",
        "Bid Response" : "Bied reaksie",
        "Total Payment" : "Totale betaling",
        "Sub Total" : "Subtotaal",
        "Payment Method" : "Betalings metode",
        "ACCEPT & PAY" : "AANVAAR EN BETAAL",
        "Description" : "Beskrywing",
        "Bid Details" : "Bied besonderhede",
        "No" : "Geen",
        "Yes,Continue" : "Ja, gaan voort",
        "if you delete this bid you would not be able to view or bid on this load" : "as jy hierdie bod uitvee, sal jy nie hierdie vrag kan sien of daarop kan bie nie",
        "Are you want to delete bid?" : "Wil jy bod uitvee?",
        "Your required to contact the lorry owner for further communication" : "U moet die eienaar van die vragmotor kontak vir verdere kommunikasie",
        "Material" : "Materiaal",
        "Load Process" : "Laai proses",
        "Tonnes" : "Tonne",
        "Date" : "Datum",
        "Shortly You get revert !!" : "Binnekort kry jy terug !!",
        "Name" : "Naam",
        "Request sent to Lorry Owner !" : "Versoek gestuur aan vragmotor eienaar!",
        "Find Lorry" : "Soek vir Lorry",
        "Load Details" : "Laai Besonderhede",
        "Load Posted !" : "Laai geplaas!",
        "Shortly You get leads !!" : "Binnekort kry jy leidrade !!",
        "Mobile Number" : "Selfoon nommer",
        "Drop Contact Details" : "Los kontakbesonderhede",
        "Pickup Contact Detail" : "Afhaal kontakbesonderhede",
        "Hours" : "Ure",
        "Number of hours" : "Aantal ure",
        "Not Fix" : "Nie Regmaak nie",
        "The number of hours visible load?" : "Die aantal ure sigbare vrag?",
        "What’s your expected price?" : "Wat is jou verwagte prys?",
        "Post" : "Post",
        "Amount" : "Bedrag",
        "Per Tonnes" : "Per ton",
        "Fix" : "Maak reg",
        "Select Vehicle" : "Kies Voertuig",
        "Drop Point" : "Drop Point",
        "Pickup Point" : "Optelpunt",
        "Next" : "Volgende",
        "Number of Tonnes" : "Aantal ton",
        "Material Name" : "Materiaal Naam",
        "Vehicle Type" : "Voertuig tipe",
        "Enter Amount" : "Voer Bedrag in",
        "Operating Routes" : "Bedryfsroetes",
        "Please verify your identity First" : "Verifieer asseblief eers jou identiteit",
        "Become world’s Transporter" : "Word die wêreld se vervoerder",
        "Hello.." : "Hallo..",
        "Confirm" : "Bevestig",
        "Select Payment Gateway" : "Kies Payment Gateway",
        "You haven't made any transaction using wallet yet" : "Jy het nog geen transaksie met beursie gemaak nie",
        "E-Wallet" : "E-beursie",
        "Transaction History" : "Transaksiegeskiedenis",
        "Total Earning" : "Totale verdienste",
        "Home" : "Tuis",
        "Wallet" : "Beursie",
        "Review" : "Resensie",
        "Terms & Conditions" : "terme en voorwaardes",
        "Privacy Policy" : "Privaatheidsbeleid",
        "Refer to Friends" : "Verwys na Vriende",
        "Profile" : "Profiel",
        "Contact Us" : "Kontak Ons",
        "Language" : "Taal",
        "FAQ" : "Gereelde vrae",
        "LogOut" : "Teken uit",
        "My Loads" : "My vragte",
        "Booked Lorries" : "Vragmotors bespreek",
        "Enter new Password" : "Voer nuwe wagwoord in",
        "Submit" : "Indien",
        "No Load Placed! Currently You Don't Have Any Loads" : "Geen vrag geplaas nie! Tans het jy geen vragte nie",
        "COMPLETED" : "VOLTOOI",
        "MY CURRENT LOADS" : "MY HUIDIGE LADINGS",
        "Booked Loads" : "Bespreek Vragte",
        "Full Name" : "Volle naam",
        "Email Address" : "E-pos adres",
        "Seems you are new here, Let’s set up your profile." : "Dit lyk of jy nuut hier is, kom ons stel jou profiel op.",
        "Getting Started!" : "Aan die gang kom!",
        "Verify Account" : "Verifieer rekening",
        "Forgot Password" : "Wagwoord vergeet",
        "Sign up" : "Teken aan",
        "Resend code?" : "Herstuur kode?",
        "Password" : "Wagwoord",
        "OTP Verification" : "OTP-verifikasie",
        "Please, enter the verification code we send to your mobile " : "Voer asseblief die verifikasiekode in wat ons na jou selfoon stuur",
        "Login" : "Teken aan",
        "Forgot  Password?" : "Wagwoord vergeet?",
        "Let’s login for explore continues" : "Kom ons meld aan vir verken gaan voort",
        "Welcome Back!" : "Welkom terug!",
        "Get better rates on every deal." : "Kry beter tariewe op elke transaksie.",
        "The right load for the right truck." : "Die regte vrag vir die regte vragmotor.",
        "Search active loads by location and equipment type" : "Soek aktiewe vragte volgens ligging en tipe toerusting",
        "We match the right load to the right truck at the right price" : "Ons pas die regte vrag by die regte vragmotor teen die regte prys",
        "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "Ons bied 'n wye reeks probleemoplossingsprodukte wat ontwerp is om jou te help om meer vrag vinniger te stuur",

    },
    'be_ge': {
      "Verify" : "যাচাই করুন",
      "Indentity" : "পরিচয়",
      "Now we need to verify your identity" : "এখন আমাদের আপনার পরিচয় যাচাই করতে হবে",
      "Note" : "দ্রষ্টব্য",
      "You are required to must upload both documents after the submit button appeared" : "জমা বোতামটি উপস্থিত হওয়ার পরে আপনাকে অবশ্যই উভয় নথি আপলোড করতে হবে",
      "Document Max 1 Picture Selected From Camera" : "নথি সর্বোচ্চ 1 ছবি ক্যামেরা থেকে নির্বাচিত",
      "Document Max 2 Picture Selected From Gallery" : "ডকুমেন্ট ম্যাক্স 2 ছবি গ্যালারি থেকে নির্বাচিত",
      "Document Max 3 Picture Selected" : "নথি সর্বাধিক 3 ছবি নির্বাচিত",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "আপনার তথ্য পরীক্ষা করতে একটি পাসপোর্ট বা আইডি নিন (কমপক্ষে 2 নথি আপলোড করুন)",
      "Passport Scan" : "পাসপোর্ট স্ক্যান",
      "Haven't uploaded yet" : "এখনো আপলোড করিনি",
      "Submit All" : "সব জমা দিন",
      "Selfie with your front camera to verify your identity" : "আপনার পরিচয় যাচাই করতে আপনার সামনের ক্যামেরা দিয়ে সেলফি নিন",
      "Selfie" : "সেলফি",
      "Add Wallet" : "ওয়ালেট যোগ করুন",
      "Add" : "যোগ করুন",
      "Post Loads" : "পোস্ট লোড",
      "Notification" : "বিজ্ঞপ্তি",
      "Balance" : "ভারসাম্য",
      "Continue" : "চালিয়ে যান",
      "Accept" : "গ্রহণ করুন",
      "Payable Amount" : "প্রদেয় পরিমাণ",
      "Lorry" : "লরি",
      "Since" : "যেহেতু",
      "Expiry in" : "মেয়াদ শেষ",
      "Do you want to reject?" : "আপনি প্রত্যাখ্যান করতে চান?",
      "Rate to" : "রেট",
      "Loads" : "লোড",
      "UnLoad" : "আনলোড করুন",
      "Routes" : "রুট",
      "Rc Verified" : "আরসি যাচাই করা হয়েছে",
      "Send offer" : "অফার পাঠান",
      "Waiting for offer Response" : "প্রস্তাব প্রতিক্রিয়া জন্য অপেক্ষা",
      "Waiting for Response" : "প্রতিক্রিয়ার অপেক্ষায়",
      "Proceed" : "এগিয়ে যান",
      "Refer a Friends, Get \$50" : "একজন বন্ধুকে রেফার করুন, \$50 পান",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "আপনার রেফারেল লিঙ্ক ব্যবহার করে কেউ গান করলে \$10 ক্রেডিট পান",
      "Share" : "শেয়ার করুন",
      "Edit Profile" : "প্রোফাইল সম্পাদনা করুন",
      "Update" : "আপডেট",
      "Post Load" : "পোস্ট লোড",
      "It is not possible to choose a larry with a your load capacity" : "আপনার লোড ক্ষমতা সহ একটি ল্যারি বেছে নেওয়া সম্ভব নয়",
      "Fixed" : "স্থির",
      "Tonne" : "টন",
      "Edit Load" : "লোড সম্পাদনা করুন",
      "Contact Details" : "যোগাযোগের বিবরণ",
      "My Self" : "আমার স্বয়ং",
      "Load Edited !" : "লোড সম্পাদিত!",
      "Enter Your Loction" : "আপনার অবস্থান লিখুন",
      "Select Vehicle type for your load" : "আপনার লোডের জন্য গাড়ির ধরন নির্বাচন করুন",
      "Available" : "পাওয়া যায়",
      "Search" : "অনুসন্ধান করুন",
      "Book Now" : "এখন বুক করুন",
      "Sent Request" : "অনুরোধ পাঠানো হয়েছে",
      "Simplify the way you find carriers." : "আপনি যেভাবে ক্যারিয়ার খুঁজে পান তা সহজ করুন।",
      "Don’t have an account?  " : "একটি অ্যাকাউন্ট নেই?",
      "Skip" : "এড়িয়ে যান",
      "Faq" : "প্রশ্ন",
      "Continue With Wallet" : "ওয়ালেট দিয়ে চালিয়ে যান",
      "Wallet information" : "ওয়ালেট তথ্য",
      "Enter your Price" : "আপনার মূল্য লিখুন",
      "Bid Now" : "আঘাত কর",
      "Reject" : "প্রত্যাখ্যান করুন",
      "offer" : "অফার",
      "Load Tracking Status" : "লোড ট্র্যাকিং অবস্থা",
      "Accept & Pay" : "গ্রহণ করুন এবং অর্থ প্রদান করুন",
      "Lorry Owner Response" : "লরি মালিকের প্রতিক্রিয়া",
      "Load" : "বোঝা",
      "Info" : "তথ্য",
      "Total Review" : "মোট পর্যালোচনা",
      "Date of Joining" : "যোগদানের তারিখ",
      "Route Operation" : "রুট অপারেশন",
      "Enter your Feedback" : "আপনার প্রতিক্রিয়া লিখুন",
      "Transaction ID" : "লেনদেন নাম্বার",
      "Payment Gateway" : "পেমেন্ট গেটওয়ে",
      "Payment Information" : "পেমেন্ট তথ্য",
      "Bidder information" : "দরদাতার তথ্য",
      "Bid Response" : "বিড রেসপন্স",
      "Total Payment" : "মোট পরিশোধ",
      "Sub Total" : "উপ মোট",
      "Payment Method" : "মূল্যপরিশোধ পদ্ধতি",
      "ACCEPT & PAY" : "গ্রহণ করুন এবং অর্থ প্রদান করুন",
      "Description" : "বর্ণনা",
      "Bid Details" : "বিডের বিবরণ",
      "No" : "না",
      "Yes,Continue" : "হ্যাঁ, চালিয়ে যান",
      "if you delete this bid you would not be able to view or bid on this load" : "আপনি এই বিড মুছে ফেললে আপনি এই লোড দেখতে বা বিড করতে সক্ষম হবে না",
      "Are you want to delete bid?" : "আপনি বিড মুছে ফেলতে চান?",
      "Your required to contact the lorry owner for further communication" : "আপনার আরও যোগাযোগের জন্য লরি মালিকের সাথে যোগাযোগ করতে হবে",
      "Material" : "উপাদান",
      "Load Process" : "লোড প্রক্রিয়া",
      "Tonnes" : "টন",
      "Date" : "তারিখ",
      "Shortly You get revert !!" : "শীঘ্রই আপনি ফিরে পাবেন!!",
      "Name" : "নাম",
      "Request sent to Lorry Owner !" : "লরি মালিকের কাছে অনুরোধ পাঠানো হয়েছে!",
      "Find Lorry" : "লরি খুঁজুন",
      "Load Details" : "লোড বিবরণ",
      "Load Posted !" : "লোড পোস্ট!",
      "Shortly You get leads !!" : "শীঘ্রই আপনি লিড পাবেন!!",
      "Mobile Number" : "মোবাইল নম্বর",
      "Drop Contact Details" : "যোগাযোগের বিবরণ বাদ দিন",
      "Pickup Contact Detail" : "পিকআপ যোগাযোগের বিস্তারিত",
      "Hours" : "ঘন্টার",
      "Number of hours" : "ঘন্টার সংখ্যা",
      "Not Fix" : "ফিক্স নয়",
      "The number of hours visible load?" : "লোড দৃশ্যমান ঘন্টা সংখ্যা?",
      "What’s your expected price?" : "আপনার প্রত্যাশিত মূল্য কি?",
      "Post" : "পোস্ট",
      "Amount" : "পরিমাণ",
      "Per Tonnes" : "প্রতি টন",
      "Fix" : "ঠিক করুন",
      "Select Vehicle" : "যানবাহন নির্বাচন করুন",
      "Drop Point" : "ড্রপ পয়েন্ট",
      "Pickup Point" : "সংগ্রহের স্থান",
      "Next" : "পরবর্তী",
      "Number of Tonnes" : "টন সংখ্যা",
      "Material Name" : "উপাদানের নাম",
      "Vehicle Type" : "গাড়ির ধরন",
      "Enter Amount" : "পরিমান লিখুন",
      "Operating Routes" : "অপারেটিং রুট",
      "Please verify your identity First" : "প্রথমে আপনার পরিচয় যাচাই করুন",
      "Become world’s Transporter" : "বিশ্বের পরিবহণকারী হয়ে উঠুন",
      "Hello.." : "হ্যালো..",
      "Confirm" : "নিশ্চিত করুন",
      "Select Payment Gateway" : "পেমেন্ট গেটওয়ে নির্বাচন করুন",
      "You haven't made any transaction using wallet yet" : "আপনি এখনও ওয়ালেট ব্যবহার করে কোনো লেনদেন করেননি",
      "E-Wallet" : "ই-ওয়ালেট",
      "Transaction History" : "আপনি কি আমার সাথে কি করতে চান",
      "Total Earning" : "মোট উপার্জন",
      "Home" : "বাড়ি",
      "Wallet" : "ওয়ালেট",
      "Review" : "পুনঃমূল্যায়ন",
      "Terms & Conditions" : "শর্তাবলী",
      "Privacy Policy" : "গোপনীয়তা নীতি",
      "Refer to Friends" : "বন্ধুদের পড়ুন",
      "Profile" : "প্রোফাইল",
      "Contact Us" : "যোগাযোগ করুন",
      "Language" : "ভাষা",
      "FAQ" : "FAQ",
      "LogOut" : "প্রস্থান",
      "My Loads" : "আমার লোড",
      "Booked Lorries" : "বুক করা লরি",
      "Enter new Password" : "নতুন পাসওয়ার্ড লিখুন",
      "Submit" : "জমা দিন",
      "No Load Placed! Currently You Don't Have Any Loads" : "কোন লোড স্থাপন করা হয়েছে! বর্তমানে আপনার কোন লোড নেই",
      "COMPLETED" : "সম্পূর্ণ",
      "MY CURRENT LOADS" : "আমার বর্তমান লোড",
      "Booked Loads" : "বুক করা লোড",
      "Full Name" : "পুরো নাম",
      "Email Address" : "ইমেইল ঠিকানা",
      "Seems you are new here, Let’s set up your profile." : "মনে হচ্ছে আপনি এখানে নতুন, আপনার প্রোফাইল সেট আপ করা যাক।",
      "Getting Started!" : "শুরু হচ্ছে!",
      "Verify Account" : "এ্যাকাউন্ট নিশ্চিতকরণ",
      "Forgot Password" : "পাসওয়ার্ড ভুলে গেছেন",
      "Sign up" : "নিবন্ধন করুন",
      "Resend code?" : "পুনরায় পাঠানো কোড?",
      "Password" : "পাসওয়ার্ড",
      "OTP Verification" : "OTP যাচাইকরণ",
      "Please, enter the verification code we send to your mobile " : "অনুগ্রহ করে, আমরা আপনার মোবাইলে যে যাচাইকরণ কোডটি পাঠাই তা লিখুন",
      "Login" : "প্রবেশ করুন",
      "Forgot  Password?" : "পাসওয়ার্ড ভুলে গেছেন?",
      "Let’s login for explore continues" : "অন্বেষণ অব্যাহত জন্য লগইন করা যাক",
      "Welcome Back!" : "ফিরে আসার জন্য স্বাগতম!",
      "Get better rates on every deal." : "প্রতিটি চুক্তিতে আরও ভাল হার পান।",
      "The right load for the right truck." : "সঠিক ট্রাকের জন্য সঠিক লোড।",
      "Search active loads by location and equipment type" : "অবস্থান এবং সরঞ্জামের ধরন দ্বারা সক্রিয় লোড খুঁজুন",
      "We match the right load to the right truck at the right price" : "আমরা সঠিক দামে সঠিক ট্রাকে সঠিক লোড মেলে",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "আমরা আপনাকে আরও দ্রুত মালবাহী জাহাজে সহায়তা করার জন্য ডিজাইন করা সমস্যা-সমাধান পণ্যগুলির একটি বিস্তৃত পরিসর অফার করি",
    },
    'sp_GE': {
      "Verify" : "Verificar",
      "Indentity" : "Identidad",
      "Now we need to verify your identity" : "Ahora necesitamos verificar tu identidad.",
      "Note" : "Nota",
      "You are required to must upload both documents after the submit button appeared" : "Debe cargar ambos documentos después de que aparezca el botón Enviar.",
      "Document Max 1 Picture Selected From Camera" : "Documento Máximo 1 imagen seleccionada de la cámara",
      "Document Max 2 Picture Selected From Gallery" : "Documento máximo 2 imágenes seleccionadas de la galería",
      "Document Max 3 Picture Selected" : "Documento Máximo 3 imágenes seleccionadas",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Lleve un pasaporte o identificación para verificar su información (cargue al menos 2 documentos)",
      "Passport Scan" : "Escaneo de pasaporte",
      "Haven't uploaded yet" : "Aún no lo he subido",
      "Submit All" : "Enviar todo",
      "Selfie with your front camera to verify your identity" : "Selfie con tu cámara frontal para verificar tu identidad",
      "Selfie" : "autofoto",
      "Add Wallet" : "Agregar billetera",
      "Add" : "Agregar",
      "Post Loads" : "Publicar cargas",
      "Notification" : "Notificación",
      "Balance" : "Balance",
      "Continue" : "Continuar",
      "Accept" : "Aceptar",
      "Payable Amount" : "Monto a pagar",
      "Lorry" : "Camión",
      "Since" : "Desde",
      "Expiry in" : "Caducidad en",
      "Do you want to reject?" : "¿Quieres rechazar?",
      "Rate to" : "Tarifa a",
      "Loads" : "Cargas",
      "UnLoad" : "Descargar",
      "Routes" : "Rutas",
      "Rc Verified" : "Rc Verificado",
      "Send offer" : "Enviar oferta",
      "Waiting for offer Response" : "Esperando oferta Respuesta",
      "Waiting for Response" : "Esperando respuesta",
      "Proceed" : "Proceder",
      "Refer a Friends, Get \$50" : "Recomiende a un amigo y obtenga \$50",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "Obtenga \$10 en crédito cuando alguien se registre usando su enlace de referencia",
      "Share" : "Compartir",
      "Edit Profile" : "Editar perfil",
      "Update" : "Actualizar",
      "Post Load" : "Publicar carga",
      "It is not possible to choose a larry with a your load capacity" : "No es posible elegir un Larry con tu capacidad de carga.",
      "Fixed" : "Fijado",
      "Tonne" : "Tonelada",
      "Edit Load" : "Editar carga",
      "Contact Details" : "Detalles de contacto",
      "My Self" : "Mí mismo",
      "Load Edited !" : "Cargar Editado!",
      "Enter Your Loction" : "Ingrese su ubicación",
      "Select Vehicle type for your load" : "Seleccione el tipo de vehículo para su carga",
      "Available" : "Disponible",
      "Search" : "Buscar",
      "Book Now" : "Reserva ahora",
      "Sent Request" : "Solicitud enviada",
      "Simplify the way you find carriers." : "Simplifique la forma de encontrar transportistas.",
      "Don’t have an account?  " : "¿No tienes una cuenta?",
      "Skip" : "Saltar",
      "Faq" : "Preguntas más frecuentes",
      "Continue With Wallet" : "Continuar con billetera",
      "Wallet information" : "Información de billetera",
      "Enter your Price" : "Introduce tu precio",
      "Bid Now" : "Haga su oferta",
      "Reject" : "Rechazar",
      "offer" : "oferta",
      "Load Tracking Status" : "Estado de seguimiento de carga",
      "Accept & Pay" : "Aceptar y pagar",
      "Lorry Owner Response" : "Respuesta del propietario del camión",
      "Load" : "Carga",
      "Info" : "Información",
      "Total Review" : "Revisión total",
      "Date of Joining" : "Fecha de inscripción",
      "Route Operation" : "Operación de ruta",
      "Enter your Feedback" : "Ingrese sus comentarios",
      "Transaction ID" : "ID de transacción",
      "Payment Gateway" : "Pasarela de pago",
      "Payment Information" : "Información del pago",
      "Bidder information" : "Información del postor",
      "Bid Response" : "Respuesta a la oferta",
      "Total Payment" : "Pago total",
      "Sub Total" : "Subtotal",
      "Payment Method" : "Método de pago",
      "ACCEPT & PAY" : "ACEPTAR Y PAGAR",
      "Description" : "Descripción",
      "Bid Details" : "Detalles de la oferta",
      "No" : "No",
      "Yes,Continue" : "Sí, continuar",
      "if you delete this bid you would not be able to view or bid on this load" : "Si elimina esta oferta, no podrá ver ni ofertar por esta carga.",
      "Are you want to delete bid?" : "¿Quieres eliminar la oferta?",
      "Your required to contact the lorry owner for further communication" : "Es necesario que se comunique con el propietario del camión para comunicarse más.",
      "Material" : "Material",
      "Load Process" : "Proceso de carga",
      "Tonnes" : "Toneladas",
      "Date" : "Fecha",
      "Shortly You get revert !!" : "¡¡En breve podrás revertir !!",
      "Name" : "Nombre",
      "Request sent to Lorry Owner !" : "¡Solicitud enviada al propietario del camión!",
      "Find Lorry" : "encontrar camión",
      "Load Details" : "Detalles de carga",
      "Load Posted !" : "Cargar Publicado!",
      "Shortly You get leads !!" : "¡¡En breve obtendrás clientes potenciales!!",
      "Mobile Number" : "Número de teléfono móvil",
      "Drop Contact Details" : "Dejar detalles de contacto",
      "Pickup Contact Detail" : "Detalle de contacto de recogida",
      "Hours" : "Horas",
      "Number of hours" : "Número de horas",
      "Not Fix" : "No arreglar",
      "The number of hours visible load?" : "¿El número de horas de carga visible?",
      "What’s your expected price?" : "¿Cuál es su precio esperado?",
      "Post" : "Correo",
      "Amount" : "Cantidad",
      "Per Tonnes" : "Por toneladas",
      "Fix" : "Arreglar",
      "Select Vehicle" : "Seleccionar vehículo",
      "Drop Point" : "Punto de entrega",
      "Pickup Point" : "Punto de recogida",
      "Next" : "Próximo",
      "Number of Tonnes" : "Número de toneladas",
      "Material Name" : "Nombre del material",
      "Vehicle Type" : "tipo de vehiculo",
      "Enter Amount" : "Ingrese el monto",
      "Operating Routes" : "Rutas operativas",
      "Please verify your identity First" : "Por favor verifique su identidad primero",
      "Become world’s Transporter" : "Conviértete en el transportador del mundo",
      "Hello.." : "Hola..",
      "Confirm" : "Confirmar",
      "Select Payment Gateway" : "Seleccione Pasarela de Pago",
      "You haven't made any transaction using wallet yet" : "Aún no has realizado ninguna transacción usando tu billetera",
      "E-Wallet" : "Monedero electrónico",
      "Transaction History" : "Historial de transacciones",
      "Total Earning" : "Ganancia total",
      "Home" : "Hogar",
      "Wallet" : "Billetera",
      "Review" : "Revisar",
      "Terms & Conditions" : "Términos y condiciones",
      "Privacy Policy" : "política de privacidad",
      "Refer to Friends" : "Referirse a amigos",
      "Profile" : "Perfil",
      "Contact Us" : "Contáctenos",
      "Language" : "Idioma",
      "FAQ" : "Preguntas más frecuentes",
      "LogOut" : "Cerrar sesión",
      "My Loads" : "mis cargas",
      "Booked Lorries" : "Camiones reservados",
      "Enter new Password" : "Ingrese nueva clave",
      "Submit" : "Entregar",
      "No Load Placed! Currently You Don't Have Any Loads" : "¡Sin carga colocada! Actualmente no tienes ninguna carga",
      "COMPLETED" : "TERMINADO",
      "MY CURRENT LOADS" : "MIS CARGAS ACTUALES",
      "Booked Loads" : "Cargas reservadas",
      "Full Name" : "Nombre completo",
      "Email Address" : "Dirección de correo electrónico",
      "Seems you are new here, Let’s set up your profile." : "Parece que eres nuevo aquí. Configuremos tu perfil.",
      "Getting Started!" : "¡Empezando!",
      "Verify Account" : "Verificar Cuenta",
      "Forgot Password" : "Has olvidado tu contraseña",
      "Sign up" : "Inscribirse",
      "Resend code?" : "¿Reenviar codigo?",
      "Password" : "Contraseña",
      "OTP Verification" : "Verificación OTP",
      "Please, enter the verification code we send to your mobile " : "Por favor, introduce el código de verificación que te enviamos a tu móvil",
      "Login" : "Acceso",
      "Forgot  Password?" : "¿Has olvidado tu contraseña?",
      "Let’s login for explore continues" : "Iniciemos sesión para explorar continúa",
      "Welcome Back!" : "¡Bienvenido de nuevo!",
      "Get better rates on every deal." : "Obtenga mejores tarifas en cada oferta.",
      "The right load for the right truck." : "La carga adecuada para el camión adecuado.",
      "Search active loads by location and equipment type" : "Buscar cargas activas por ubicación y tipo de equipo",
      "We match the right load to the right truck at the right price" : "Combinamos la carga adecuada con el camión adecuado al precio adecuado",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "Ofrecemos una amplia gama de productos de resolución de problemas diseñados para ayudarle a enviar más carga más rápido",
    },
    'hi_IN': {
      "Verify" : "सत्यापित करें",
      "Indentity" : "इंडेंटिटी",
      "Now we need to verify your identity" : "अब हमें आपकी पहचान सत्यापित करने की आवश्यकता है",
      "Note" : "टिप्पणी",
      "You are required to must upload both documents after the submit button appeared" : "सबमिट बटन दिखाई देने के बाद आपको दोनों दस्तावेज़ अपलोड करने होंगे",
      "Document Max 1 Picture Selected From Camera" : "दस्तावेज़ अधिकतम 1 चित्र कैमरे से चयनित",
      "Document Max 2 Picture Selected From Gallery" : "गैलरी से चयनित दस्तावेज़ मैक्स 2 चित्र",
      "Document Max 3 Picture Selected" : "दस्तावेज़ अधिकतम 3 चित्र चयनित",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "अपनी जानकारी जांचने के लिए पासपोर्ट या आईडी लें (कम से कम 2 दस्तावेज़ अपलोड करें)",
      "Passport Scan" : "पासपोर्ट स्कैन",
      "Haven't uploaded yet" : "अभी तक अपलोड नहीं किया है",
      "Submit All" : "सभी को प्रस्तुत करें",
      "Selfie with your front camera to verify your identity" : "अपनी पहचान सत्यापित करने के लिए अपने फ्रंट कैमरे से सेल्फी लें",
      "Selfie" : "सेल्फी",
      "Add Wallet" : "वॉलेट जोड़ें",
      "Add" : "जोड़ना",
      "Post Loads" : "पोस्ट लोड",
      "Notification" : "अधिसूचना",
      "Balance" : "संतुलन",
      "Continue" : "जारी रखना",
      "Accept" : "स्वीकार करना",
      "Payable Amount" : "देय राशि",
      "Lorry" : "लॉरी",
      "Since" : "तब से",
      "Expiry in" : "में समाप्ति",
      "Do you want to reject?" : "क्या आप अस्वीकार करना चाहते हैं?",
      "Rate to" : "को रेट करें",
      "Loads" : "भार",
      "UnLoad" : "उतारना",
      "Routes" : "मार्गों",
      "Rc Verified" : "आरसी सत्यापित",
      "Send offer" : "प्रस्ताव भेजें",
      "Waiting for offer Response" : "प्रस्ताव प्रतिक्रिया की प्रतीक्षा में",
      "Waiting for Response" : "प्रतिक्रिया के लिए प्रतीक्षा कर रहा हूँ",
      "Proceed" : "आगे बढ़ना",
      "Refer a Friends, Get \$50" : "किसी मित्र को रेफ़र करें, \$50 पाएँ",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "जब कोई आपके रेफ़रल लिंक का उपयोग करके गाना गाता है तो \$10 का क्रेडिट प्राप्त करें",
      "Share" : "शेयर करना",
      "Edit Profile" : "प्रोफ़ाइल संपादित करें",
      "Update" : "अद्यतन",
      "Post Load" : "पोस्ट लोड",
      "It is not possible to choose a larry with a your load capacity" : "आपकी भार क्षमता के अनुरूप लैरी का चयन करना संभव नहीं है",
      "Fixed" : "तय",
      "Tonne" : "टन",
      "Edit Load" : "लोड संपादित करें",
      "Contact Details" : "सम्पर्क करने का विवरण",
      "My Self" : "खुद",
      "Load Edited !" : "लोड संपादित!",
      "Enter Your Loction" : "अपना स्थान दर्ज करें",
      "Select Vehicle type for your load" : "अपने भार के लिए वाहन का प्रकार चुनें",
      "Available" : "उपलब्ध",
      "Search" : "खोज",
      "Book Now" : "अभी बुक करें",
      "Sent Request" : "अनुरोध भेजा गया",
      "Simplify the way you find carriers." : "वाहक ढूंढने का तरीका सरल बनाएं.",
      "Don’t have an account?  " : "कोई खाता नहीं है?",
      "Skip" : "छोडना",
      "Faq" : "सामान्य प्रश्न",
      "Continue With Wallet" : "वॉलेट के साथ जारी रखें",
      "Wallet information" : "बटुए की जानकारी",
      "Enter your Price" : "अपना मूल्य दर्ज करें",
      "Bid Now" : "बोली लगाओ",
      "Reject" : "अस्वीकार करना",
      "offer" : "प्रस्ताव",
      "Load Tracking Status" : "ट्रैकिंग स्थिति लोड करें",
      "Accept & Pay" : "स्वीकार करें और भुगतान करें",
      "Lorry Owner Response" : "लॉरी मालिक की प्रतिक्रिया",
      "Load" : "भार",
      "Info" : "जानकारी",
      "Total Review" : "कुल समीक्षा",
      "Date of Joining" : "शामिल होने की तिथि",
      "Route Operation" : "मार्ग संचालन",
      "Enter your Feedback" : "अपनी प्रतिक्रिया दर्ज करें",
      "Transaction ID" : "लेन-देन आईडी",
      "Payment Gateway" : "भुगतान गेटवे",
      "Payment Information" : "भुगतान जानकारी",
      "Bidder information" : "बोली लगाने वाले की जानकारी",
      "Bid Response" : "बोली प्रतिक्रिया",
      "Total Payment" : "कुल भुगतान",
      "Sub Total" : "उप योग",
      "Payment Method" : "भुगतान विधि",
      "ACCEPT & PAY" : "स्वीकार करें और भुगतान करें",
      "Description" : "विवरण",
      "Bid Details" : "बोली विवरण",
      "No" : "नहीं",
      "Yes,Continue" : "हाँ, जारी रखें",
      "if you delete this bid you would not be able to view or bid on this load" : "यदि आप इस बोली को हटा देते हैं तो आप इस लोड को देख या बोली नहीं लगा पाएंगे",
      "Are you want to delete bid?" : "क्या आप बोली हटाना चाहते हैं?",
      "Your required to contact the lorry owner for further communication" : "आगे की बातचीत के लिए आपको लॉरी मालिक से संपर्क करना होगा",
      "Material" : "सामग्री",
      "Load Process" : "लोड प्रक्रिया",
      "Tonnes" : "टन",
      "Date" : "तारीख",
      "Shortly You get revert !!" : "शीघ्र ही आपको उत्तर मिलेगा!!",
      "Name" : "नाम",
      "Request sent to Lorry Owner !" : "लॉरी मालिक को अनुरोध भेजा गया!",
      "Find Lorry" : "लॉरी ढूंढो",
      "Load Details" : "विवरण लोड करें",
      "Load Posted !" : "लोड पोस्ट किया गया!",
      "Shortly You get leads !!" : "शीघ्र ही आपको लीड मिल जाएगी!!",
      "Mobile Number" : "मोबाइल नंबर",
      "Drop Contact Details" : "संपर्क विवरण छोड़ें",
      "Pickup Contact Detail" : "पिकअप संपर्क विवरण",
      "Hours" : "घंटे",
      "Number of hours" : "घंटों की संख्या",
      "Not Fix" : "तय नहीं",
      "The number of hours visible load?" : "दृश्यमान लोड घंटों की संख्या?",
      "What’s your expected price?" : "आपकी अपेक्षित कीमत क्या है?",
      "Post" : "डाक",
      "Amount" : "मात्रा",
      "Per Tonnes" : "प्रति टन",
      "Fix" : "हल करना",
      "Select Vehicle" : "वाहन का चयन करें",
      "Drop Point" : "ड्रॉप बिंदु",
      "Pickup Point" : "पिक अप बिंदु",
      "Next" : "अगला",
      "Number of Tonnes" : "टन की संख्या",
      "Material Name" : "सामग्री नाम",
      "Vehicle Type" : "वाहन का प्रकार",
      "Enter Amount" : "राशि डालें",
      "Operating Routes" : "परिचालन मार्ग",
      "Please verify your identity First" : "कृपया पहले अपनी पहचान सत्यापित करें",
      "Become world’s Transporter" : "दुनिया के ट्रांसपोर्टर बनें",
      "Hello.." : "नमस्ते..",
      "Confirm" : "पुष्टि करना",
      "Select Payment Gateway" : "पेमेंट गेटवे चुनें",
      "You haven't made any transaction using wallet yet" : "आपने अभी तक वॉलेट का उपयोग करके कोई लेनदेन नहीं किया है",
      "E-Wallet" : "ई-बटुआ",
      "Transaction History" : "ट्रांजेक्शन इतिहास",
      "Total Earning" : "कुल कमाई",
      "Home" : "घर",
      "Wallet" : "बटुआ",
      "Review" : "समीक्षा",
      "Terms & Conditions" : "नियम एवं शर्तें",
      "Privacy Policy" : "गोपनीयता नीति",
      "Refer to Friends" : "मित्रों का संदर्भ लें",
      "Profile" : "प्रोफ़ाइल",
      "Contact Us" : "संपर्क करें",
      "Language" : "भाषा",
      "FAQ" : "सामान्य प्रश्न",
      "LogOut" : "लॉग आउट",
      "My Loads" : "मेरा भार",
      "Booked Lorries" : "लॉरीज़ बुक कीं",
      "Enter new Password" : "नया पासवर्ड दर्ज करें",
      "Submit" : "जमा करना",
      "No Load Placed! Currently You Don't Have Any Loads" : "कोई भार नहीं डाला गया! वर्तमान में आपके पास कोई भार नहीं है",
      "COMPLETED" : "पुरा होना",
      "MY CURRENT LOADS" : "मेरा वर्तमान भार",
      "Booked Loads" : "बहुत सारा सामान बुक किया गया",
      "Full Name" : "पूरा नाम",
      "Email Address" : "मेल पता",
      "Seems you are new here, Let’s set up your profile." : "लगता है आप यहां नए हैं, चलिए आपकी प्रोफ़ाइल सेट करते हैं।",
      "Getting Started!" : "शुरू करना!",
      "Verify Account" : "खाता सत्यापित करें",
      "Forgot Password" : "पासवर्ड भूल गए",
      "Sign up" : "साइन अप करें",
      "Resend code?" : "पुन: कोड भेजे?",
      "Password" : "पासवर्ड",
      "OTP Verification" : "ओटीपी सत्यापन",
      "Please, enter the verification code we send to your mobile " : "कृपया, हमारे द्वारा आपके मोबाइल पर भेजा गया सत्यापन कोड दर्ज करें",
      "Login" : "लॉग इन करें",
      "Forgot  Password?" : "पासवर्ड भूल गए?",
      "Let’s login for explore continues" : "आइए एक्सप्लोर जारी रखने के लिए लॉगिन करें",
      "Welcome Back!" : "वापसी पर स्वागत है!",
      "Get better rates on every deal." : "प्रत्येक सौदे पर बेहतर दरें प्राप्त करें।",
      "The right load for the right truck." : "सही ट्रक के लिए सही लोड.",
      "Search active loads by location and equipment type" : "स्थान और उपकरण प्रकार के आधार पर सक्रिय लोड खोजें",
      "We match the right load to the right truck at the right price" : "हम सही कीमत पर सही ट्रक से सही लोड का मिलान करते हैं",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "हम आपको अधिक माल तेजी से भेजने में मदद करने के लिए डिज़ाइन किए गए समस्या-समाधान उत्पादों की एक विस्तृत श्रृंखला पेश करते हैं",
    },
    'ge_In': {
      "Verify" : "ચકાસો",
      "Indentity" : "ઓળખાણ",
      "Now we need to verify your identity" : "હવે અમારે તમારી ઓળખ ચકાસવાની જરૂર છે",
      "Note" : "નોંધ",
      "You are required to must upload both documents after the submit button appeared" : "સબમિટ બટન દેખાય તે પછી તમારે બંને દસ્તાવેજો અપલોડ કરવા આવશ્યક છે",
      "Document Max 1 Picture Selected From Camera" : "દસ્તાવેજ મહત્તમ 1 ચિત્ર કેમેરામાંથી પસંદ કરેલ",
      "Document Max 2 Picture Selected From Gallery" : "દસ્તાવેજ મેક્સ 2 ચિત્ર ગેલેરીમાંથી પસંદ કરેલ",
      "Document Max 3 Picture Selected" : "દસ્તાવેજ મહત્તમ 3 ચિત્ર પસંદ કર્યું",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "તમારી માહિતી તપાસવા માટે પાસપોર્ટ અથવા ID લો (ઓછામાં ઓછા 2 દસ્તાવેજ અપલોડ કરો)",
      "Passport Scan" : "પાસપોર્ટ સ્કેન",
      "Haven't uploaded yet" : "હજુ સુધી અપલોડ કર્યું નથી",
      "Submit All" : "બધા સબમિટ કરો",
      "Selfie with your front camera to verify your identity" : "તમારી ઓળખ ચકાસવા માટે તમારા ફ્રન્ટ કેમેરા વડે સેલ્ફી લો",
      "Selfie" : "સેલ્ફી",
      "Add" : "ઉમેરો",
      "Add Wallet" : "વૉલેટ ઉમેરો",
      "Post Loads" : "પોસ્ટ લોડ્સ",
      "Notification" : "સૂચના",
      "Balance" : "સંતુલન",
      "Continue" : "ચાલુ રાખો",
      "Accept" : "સ્વીકારો",
      "Payable Amount" : "ચૂકવવાપાત્ર રકમ",
      "Lorry" : "લારી",
      "Since" : "ત્યારથી",
      "Expiry in" : "માં સમાપ્ત થાય છે",
      "Do you want to reject?" : "શું તમે નકારવા માંગો છો?",
      "Rate to" : "માટે દર",
      "Loads" : "લોડ્સ",
      "UnLoad" : "અનલોડ કરો",
      "Routes" : "માર્ગો",
      "Rc Verified" : "આરસી વેરિફાઈડ",
      "Send offer" : "ઓફર મોકલો",
      "Waiting for offer Response" : "ઑફર પ્રતિસાદની રાહ જોઈ રહ્યાં છીએ",
      "Waiting for Response" : "પ્રતિભાવની રાહ જોઈ રહ્યા છીએ",
      "Proceed" : "આગળ વધો",
      "Refer a Friends, Get \$50" : "મિત્રોનો સંદર્ભ લો, \$50 મેળવો",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "જ્યારે કોઈ તમારી રેફરલ લિંકનો ઉપયોગ કરીને ગીત ગાશે ત્યારે \$10 ક્રેડિટ મેળવો",
      "Share" : "શેર કરો",
      "Edit Profile" : "પ્રોફાઇલ સંપાદિત કરો",
      "Update" : "અપડેટ કરો",
      "Post Load" : "પોસ્ટ લોડ",
      "It is not possible to choose a larry with a your load capacity" : "તમારી લોડ ક્ષમતા સાથે લારી પસંદ કરવી શક્ય નથી",
      "Fixed" : "સ્થિર",
      "Tonne" : "ટન",
      "Edit Load" : "લોડ સંપાદિત કરો",
      "Contact Details" : "સંપર્ક વિગતો",
      "My Self" : "માય સેલ્ફ",
      "Load Edited !" : "લોડ સંપાદિત!",
      "Enter Your Loction" : "તમારું સ્થાન દાખલ કરો",
      "Select Vehicle type for your load" : "તમારા લોડ માટે વાહનનો પ્રકાર પસંદ કરો",
      "Available" : "ઉપલબ્ધ છે",
      "Search" : "શોધો",
      "Book Now" : "હવે બુક કરો",
      "Sent Request" : "વિનંતી મોકલી",
      "Simplify the way you find carriers." : "તમને કેરિયર્સ શોધવાની રીતને સરળ બનાવો.",
      "Don’t have an account?  " : "ખાતું નથી?",
      "Skip" : "છોડો",
      "Faq" : "FAQ",
      "Continue With Wallet" : "વૉલેટ સાથે ચાલુ રાખો",
      "Wallet information" : "વૉલેટ માહિતી",
      "Enter your Price" : "તમારી કિંમત દાખલ કરો",
      "Bid Now" : "હવે બિડ કરો",
      "Reject" : "અસ્વીકાર કરો",
      "offer" : "ઓફર",
      "Load Tracking Status" : "લોડ ટ્રેકિંગ સ્થિતિ",
      "Accept & Pay" : "સ્વીકારો અને ચૂકવો",
      "Lorry Owner Response" : "લોરી માલિક પ્રતિભાવ",
      "Load" : "લોડ",
      "Info" : "માહિતી",
      "Total Review" : "કુલ સમીક્ષા",
      "Date of Joining" : "જોડાવાની તારીખ",
      "Route Operation" : "રૂટ ઓપરેશન",
      "Enter your Feedback" : "તમારો પ્રતિસાદ દાખલ કરો",
      "Transaction ID" : "ટ્રાન્ઝેક્શન આઈડી",
      "Payment Gateway" : "પેમેન્ટ ગેટવે",
      "Payment Information" : "ચુકવણી માહિતી",
      "Bidder information" : "બિડર માહિતી",
      "Bid Response" : "બિડ પ્રતિસાદ",
      "Total Payment" : "કુલ ચુકવણી",
      "Sub Total" : "પેટા કુલ",
      "Payment Method" : "ચુકવણી પદ્ધતિ",
      "ACCEPT & PAY" : "સ્વીકારો અને ચૂકવો",
      "Description" : "વર્ણન",
      "Bid Details" : "બિડ વિગતો",
      "No" : "ના",
      "Yes,Continue" : "હા, ચાલુ રાખો",
      "if you delete this bid you would not be able to view or bid on this load" : "જો તમે આ બિડ કાઢી નાખો છો, તો તમે આ લોડને જોઈ કે બિડ કરી શકશો નહીં",
      "Are you want to delete bid?" : "શું તમે બિડ કાઢી નાખવા માંગો છો?",
      "Your required to contact the lorry owner for further communication" : "વધુ સંચાર માટે તમારે લોરી માલિકનો સંપર્ક કરવો જરૂરી છે",
      "Material" : "સામગ્રી",
      "Load Process" : "લોડ પ્રક્રિયા",
      "Tonnes" : "ટન",
      "Date" : "તારીખ",
      "Shortly You get revert !!" : "ટૂંક સમયમાં તમે પાછા ફરો !!",
      "Name" : "નામ",
      "Request sent to Lorry Owner !" : "લોરીના માલિકને વિનંતી મોકલી!",
      "Find Lorry" : "લોરી શોધો",
      "Load Details" : "લોડ વિગતો",
      "Load Posted !" : "લોડ પોસ્ટ કર્યું!",
      "Shortly You get leads !!" : "ટૂંક સમયમાં તમને લીડ્સ મળશે !!",
      "Mobile Number" : "મોબાઇલ નંબર",
      "Drop Contact Details" : "સંપર્ક વિગતો મૂકો",
      "Pickup Contact Detail" : "પિકઅપ સંપર્ક વિગતો",
      "Hours" : "કલાકો",
      "Number of hours" : "કલાકોની સંખ્યા",
      "Not Fix" : "ફિક્સ નથી",
      "The number of hours visible load?" : "દૃશ્યમાન લોડના કલાકોની સંખ્યા?",
      "What’s your expected price?" : "તમારી અપેક્ષિત કિંમત શું છે?",
      "Post" : "પોસ્ટ",
      "Amount" : "રકમ",
      "Per Tonnes" : "પ્રતિ ટન",
      "Fix" : "ઠીક કરો",
      "Select Vehicle" : "વાહન પસંદ કરો",
      "Drop Point" : "ડ્રોપ પોઈન્ટ",
      "Pickup Point" : "પિકઅપ પોઈન્ટ",
      "Next" : "આગળ",
      "Number of Tonnes" : "ટનની સંખ્યા",
      "Material Name" : "સામગ્રીનું નામ",
      "Vehicle Type" : "વાહનનો પ્રકાર",
      "Enter Amount" : "રકમ દાખલ કરો",
      "Operating Routes" : "ઓપરેટિંગ રૂટ્સ",
      "Please verify your identity First" : "કૃપા કરીને પહેલા તમારી ઓળખ ચકાસો",
      "Become world’s Transporter" : "વિશ્વના ટ્રાન્સપોર્ટર બનો",
      "Hello.." : "નમસ્તે..",
      "Confirm" : "પુષ્ટિ કરો",
      "Select Payment Gateway" : "પેમેન્ટ ગેટવે પસંદ કરો",
      "You haven't made any transaction using wallet yet" : "તમે હજી સુધી વૉલેટનો ઉપયોગ કરીને કોઈ વ્યવહાર કર્યો નથી",
      "E-Wallet" : "ઇ-વોલેટ",
      "Transaction History" : "વ્યવહાર ઇતિહાસ",
      "Total Earning" : "કુલ કમાણી",
      "Home" : "ઘર",
      "Wallet" : "વૉલેટ",
      "Review" : "સમીક્ષા",
      "Terms & Conditions" : "શરતો અને નિયમો",
      "Privacy Policy" : "ગોપનીયતા નીતિ",
      "Refer to Friends" : "મિત્રો નો સંદર્ભ લો",
      "Profile" : "પ્રોફાઇલ",
      "Contact Us" : "અમારો સંપર્ક કરો",
      "Language" : "ભાષા",
      "FAQ" : "FAQ",
      "LogOut" : "લૉગ આઉટ",
      "My Loads" : "મારા લોડ્સ",
      "Booked Lorries" : "લોરીઓ બુક કરાવી",
      "Enter new Password" : "નવો પાસવર્ડ દાખલ કરો",
      "Submit" : "સબમિટ કરો",
      "No Load Placed! Currently You Don't Have Any Loads" : "કોઈ લોડ મૂકવામાં આવ્યું નથી! હાલમાં તમારી પાસે કોઈ ભાર નથી",
      "COMPLETED" : "પૂર્ણ થયું",
      "MY CURRENT LOADS" : "મારા વર્તમાન લોડ્સ",
      "Booked Loads" : "બુક કરાવેલ લોડ",
      "Full Name" : "પૂરું નામ",
      "Email Address" : "ઈ - મેઈલ સરનામું",
      "Seems you are new here, Let’s set up your profile." : "લાગે છે કે તમે અહીં નવા છો, ચાલો તમારી પ્રોફાઇલ સેટ કરીએ.",
      "Getting Started!" : "પ્રારંભ કરો!",
      "Verify Account" : "એકાઉન્ટ ચકાસો",
      "Forgot Password" : "પાસવર્ડ ભૂલી ગયા છો",
      "Sign up" : "સાઇન અપ કરો",
      "Resend code?" : "કોડ ફરીથી મોકલીએ?",
      "Password" : "પાસવર્ડ",
      "OTP Verification" : "OTP ચકાસણી",
      "Please, enter the verification code we send to your mobile " : "કૃપા કરીને, અમે તમારા મોબાઇલ પર મોકલીએ છીએ તે ચકાસણી કોડ દાખલ કરો",
      "Login" : "પ્રવેશ કરો",
      "Forgot  Password?" : "પાસવર્ડ ભૂલી ગયા છો?",
      "Let’s login for explore continues" : "ચાલો અન્વેષણ ચાલુ રાખવા માટે લૉગિન કરીએ",
      "Welcome Back!" : "ફરી સ્વાગત છે!",
      "Get better rates on every deal." : "દરેક સોદા પર વધુ સારા દરો મેળવો.",
      "The right load for the right truck." : "જમણી ટ્રક માટે યોગ્ય લોડ.",
      "Search active loads by location and equipment type" : "સ્થાન અને સાધનોના પ્રકાર દ્વારા સક્રિય લોડ શોધો",
      "We match the right load to the right truck at the right price" : "અમે યોગ્ય કિંમતે યોગ્ય ટ્રક સાથે યોગ્ય ભારને મેચ કરીએ છીએ",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "અમે તમને વધુ નૂર ઝડપથી મોકલવામાં મદદ કરવા માટે રચાયેલ સમસ્યા-નિરાકરણ ઉત્પાદનોની વિશાળ શ્રેણી ઑફર કરીએ છીએ",
    },
    'Id_Ge': {
      "Verify" : "Memeriksa",
      "Indentity" : "Identitas",
      "Now we need to verify your identity" : "Sekarang kami perlu memverifikasi identitas Anda",
      "Note" : "Catatan",
      "You are required to must upload both documents after the submit button appeared" : "Anda diharuskan mengunggah kedua dokumen tersebut setelah tombol kirim muncul",
      "Document Max 1 Picture Selected From Camera" : "Dokumen Maks 1 Gambar Dipilih Dari Kamera",
      "Document Max 2 Picture Selected From Gallery" : "Dokumen Maks 2 Gambar Dipilih Dari Galeri",
      "Document Max 3 Picture Selected" : "Dokumen Maks 3 Gambar Dipilih",
      "Take a Passport or ID to Check Your Information(Upload at Least 2 document)" : "Ambil Paspor atau ID untuk Memeriksa Informasi Anda (Unggah Minimal 2 dokumen)",
      "Passport Scan" : "Pemindaian Paspor",
      "Haven't uploaded yet" : "Belum diunggah",
      "Submit All" : "Kirim Semua",
      "Selfie with your front camera to verify your identity" : "Selfie dengan kamera depan Anda untuk memverifikasi identitas Anda",
      "Selfie" : "Selfie",
      "Add" : "Menambahkan",
      "Add Wallet" : "Tambahkan Dompet",
      "Post Loads" : "Beban Posting",
      "Notification" : "Pemberitahuan",
      "Balance" : "Keseimbangan",
      "Continue" : "Melanjutkan",
      "Accept" : "Menerima",
      "Payable Amount" : "Jumlah Hutang",
      "Lorry" : "Truk",
      "Since" : "Sejak",
      "Expiry in" : "Kedaluwarsa dalam",
      "Do you want to reject?" : "Apakah Anda ingin menolak?",
      "Rate to" : "Beri nilai ke",
      "Loads" : "Banyak",
      "UnLoad" : "Membongkar",
      "Routes" : "Rute",
      "Rc Verified" : "RC Terverifikasi",
      "Send offer" : "Kirim penawaran",
      "Waiting for offer Response" : "Menunggu tawaran Respon",
      "Waiting for Response" : "Menunggu Respon",
      "Proceed" : "Melanjutkan",
      "Refer a Friends, Get \$50" : "Referensikan Teman, Dapatkan \$50",
      "Get \$10 in Credit When Someone Sing Up Using Your Referal Link" : "Dapatkan Kredit \$10 Saat Seseorang Bernyanyi Menggunakan Tautan Referensi Anda",
      "Share" : "Membagikan",
      "Edit Profile" : "Sunting Profil",
      "Update" : "Memperbarui",
      "Post Load" : "Beban Pos",
      "It is not possible to choose a larry with a your load capacity" : "Tidak mungkin memilih larry dengan kapasitas muat Anda",
      "Fixed" : "Tetap",
      "Tonne" : "Ton",
      "Edit Load" : "Sunting Muat",
      "Contact Details" : "Detail Kontak",
      "My Self" : "Saya sendiri",
      "Load Edited !" : "Muat Diedit!",
      "Enter Your Loction" : "Masukkan Loksi Anda",
      "Select Vehicle type for your load" : "Pilih jenis Kendaraan untuk muatan Anda",
      "Available" : "Tersedia",
      "Search" : "Mencari",
      "Book Now" : "Pesan Sekarang",
      "Sent Request" : "Permintaan Terkirim",
      "Simplify the way you find carriers." : "Sederhanakan cara Anda menemukan operator.",
      "Don’t have an account?  " : "Belum punya akun?",
      "Skip" : "Melewati",
      "Faq" : "Pertanyaan Umum",
      "Continue With Wallet" : "Lanjutkan Dengan Dompet",
      "Wallet information" : "Informasi dompet",
      "Enter your Price" : "Masukkan Harga Anda",
      "Bid Now" : "Tawar sekarang",
      "Reject" : "Menolak",
      "offer" : "menawarkan",
      "Load Tracking Status" : "Status Pelacakan Beban",
      "Accept & Pay" : "Terima & Bayar",
      "Lorry Owner Response" : "Tanggapan Pemilik Truk",
      "Load" : "Memuat",
      "Info" : "Informasi",
      "Total Review" : "Ulasan Total",
      "Date of Joining" : "Tanggal Bergabung",
      "Route Operation" : "Operasi Rute",
      "Enter your Feedback" : "Masukkan Masukan Anda",
      "Transaction ID" : "ID transaksi",
      "Payment Gateway" : "Gerbang pembayaran",
      "Payment Information" : "Informasi Pembayaran",
      "Bidder information" : "Informasi penawar",
      "Bid Response" : "Respon Tawaran",
      "Total Payment" : "Total pembayaran",
      "Sub Total" : "Sub Jumlah",
      "Payment Method" : "Cara Pembayaran",
      "ACCEPT & PAY" : "TERIMA & BAYAR",
      "Description" : "Keterangan",
      "Bid Details" : "Detail Tawaran",
      "No" : "TIDAK",
      "Yes,Continue" : "Ya, Lanjutkan",
      "if you delete this bid you would not be able to view or bid on this load" : "jika Anda menghapus tawaran ini, Anda tidak akan dapat melihat atau menawar muatan ini",
      "Are you want to delete bid?" : "Apakah Anda ingin menghapus tawaran?",
      "Your required to contact the lorry owner for further communication" : "Anda diharuskan menghubungi pemilik truk untuk komunikasi lebih lanjut",
      "Material" : "Bahan",
      "Load Process" : "Proses Muat",
      "Tonnes" : "Ton",
      "Date" : "Tanggal",
      "Shortly You get revert !!" : "Segera Anda akan kembali !!",
      "Name" : "Nama",
      "Request sent to Lorry Owner !" : "Permintaan dikirim ke Pemilik Lorry!",
      "Find Lorry" : "Temukan truk",
      "Load Details" : "Memuat Detail",
      "Load Posted !" : "Muat Diposting!",
      "Shortly You get leads !!" : "Segera Anda mendapatkan petunjuk !!",
      "Mobile Number" : "Nomor handphone",
      "Drop Contact Details" : "Jatuhkan Detail Kontak",
      "Pickup Contact Detail" : "Detail Kontak Penjemputan",
      "Hours" : "Jam",
      "Number of hours" : "Jumlah jam",
      "Not Fix" : "Tidak pasti",
      "The number of hours visible load?" : "Jumlah jam terlihat memuat?",
      "What’s your expected price?" : "Berapa harga yang Anda harapkan?",
      "Post" : "Pos",
      "Amount" : "Jumlah",
      "Per Tonnes" : "Per Ton",
      "Fix" : "Memperbaiki",
      "Select Vehicle" : "Pilih Kendaraan",
      "Drop Point" : "Titik Jatuh",
      "Pickup Point" : "Titik Penjemputan",
      "Next" : "Berikutnya",
      "Number of Tonnes" : "Jumlah Ton",
      "Material Name" : "nama material",
      "Vehicle Type" : "Jenis Kendaraan",
      "Enter Amount" : "Masukan jumlah",
      "Operating Routes" : "Rute Operasi",
      "Please verify your identity First" : "Harap verifikasi identitas Anda terlebih dahulu",
      "Become world’s Transporter" : "Menjadi Transporter dunia",
      "Hello.." : "Halo..",
      "Confirm" : "Mengonfirmasi",
      "Select Payment Gateway" : "Pilih Gerbang Pembayaran",
      "You haven't made any transaction using wallet yet" : "Anda belum melakukan transaksi apa pun menggunakan dompet",
      "E-Wallet" : "Dompet Elektronik",
      "Transaction History" : "sejarah transaksi",
      "Total Earning" : "Jumlah Penghasilan",
      "Home" : "Rumah",
      "Wallet" : "Dompet",
      "Review" : "Tinjauan",
      "Terms & Conditions" : "Syarat & Ketentuan",
      "Privacy Policy" : "Kebijakan pribadi",
      "Refer to Friends" : "Rujuk ke Teman",
      "Profile" : "Profil",
      "Contact Us" : "Hubungi kami",
      "Language" : "Bahasa",
      "FAQ" : "Pertanyaan Umum",
      "LogOut" : "Keluar",
      "My Loads" : "Beban saya",
      "Booked Lorries" : "Truk yang dipesan",
      "Enter new Password" : "Masukan kata sandi baru",
      "Submit" : "Kirim",
      "No Load Placed! Currently You Don't Have Any Loads" : "Tidak Ada Beban yang Ditempatkan! Saat ini Anda Tidak Memiliki Beban Apa Pun",
      "COMPLETED" : "LENGKAP",
      "MY CURRENT LOADS" : "BEBAN SAYA SAAT INI",
      "Booked Loads" : "Banyak yang Dipesan",
      "Full Name" : "Nama lengkap",
      "Email Address" : "Alamat email",
      "Seems you are new here, Let’s set up your profile." : "Sepertinya Anda baru di sini, Ayo siapkan profil Anda.",
      "Getting Started!" : "Mulai!",
      "Verify Account" : "verifikasi akun",
      "Forgot Password" : "Tidak ingat kata sandi",
      "Sign up" : "Mendaftar",
      "Resend code?" : "Kirim ulang kode?",
      "Password" : "Kata sandi",
      "OTP Verification" : "Verifikasi OTP",
      "Please, enter the verification code we send to your mobile " : "Silakan masukkan kode verifikasi yang kami kirimkan ke ponsel Anda",
      "Login" : "Gabung",
      "Forgot  Password?" : "Tidak ingat kata sandi?",
      "Let’s login for explore continues" : "Ayo login untuk penjelajahan berlanjut",
      "Welcome Back!" : "Selamat Datang kembali!",
      "Get better rates on every deal." : "Dapatkan harga yang lebih baik di setiap transaksi.",
      "The right load for the right truck." : "Muatan yang tepat untuk truk yang tepat.",
      "Search active loads by location and equipment type" : "Cari beban aktif berdasarkan lokasi dan jenis peralatan",
      "We match the right load to the right truck at the right price" : "Kami mencocokkan muatan yang tepat dengan truk yang tepat dengan harga yang tepat",
      "We offer a wide range of problem-solving products designed to help you ship more freight faster" : "Kami menawarkan beragam produk pemecahan masalah yang dirancang untuk membantu Anda mengirimkan lebih banyak barang dengan lebih cepat",
    },
  };
}